channels:
  - conda-forge
  - defaults
  - mosek
  - pytorch
dependencies:
  - python
  - pip
  - pip:
    - google-cloud-batch
  - google-cloud-sdk
  - google-cloud-cpp
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - scikit-learn-intelex
  - seaborn
  - matplotlib
  - cvxpy
  - pywavelets
  - pynvim
  - pytorch
  - cupy
  - curl
  - ruby
  - make
  - cmake
  - llvm
  - tmux
  - git
  - mercurial
  - wget
  - the_silver_searcher
  - emacs
  - htop
  - mosh
  - vim
  - ripgrep
  - libclang
  - clangxx
  - clang
  - libgcc-ng
  - libstdcxx-ng
  - gcc
  - gxx
  - nodejs
  - mkl
  - mosek
  - texlive-core
  - openssl
  - rust
  - bash-completion
  - ipython
  - jupyterlab
