#!/bin/bash

set -o errexit -o nounset -o xtrace

VERSION=$(git version | awk '{print $3}')
curl https://raw.githubusercontent.com/git/git/v$VERSION/contrib/completion/git-completion.bash -o ~/.git-completion.bash
