#!/bin/bash

set -o errexit -o nounset -o xtrace

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew install bash
sudo bash -c 'echo /opt/homebrew/bin/bash >> /etc/shells'
chsh -s /opt/homebrew/bin/bash

brew install cask
brew install tmux
brew install mobile-shell
brew install coreutils
brew install git
brew install neovim

brew install google-chrome --cask
brew install signal --cask
brew install spotify --cask
brew install dashlane --cask
brew install alfred --cask
brew install firefox --cask
brew install google-backup-and-sync --cask
brew install iterm2 --cask
defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "~/.config/iterm2"
defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true
curl -L https://iterm2.com/shell_integration/install_shell_integration_and_utilities.sh | bash

brew tap wez/wezterm
brew install --cask wez/wezterm/wezterm
