#!/bin/bash

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew install mobile-shell
brew install coreutils
brew install git

brew install bash
sudo bash -c 'echo /usr/local/bin/bash >> /etc/shells'
chsh -s /usr/local/bin/bash

brew install neovim

brew install cask
brew cask install google-chrome
brew cask install iterm2
brew cask install signal
