#!/bin/bash

set -o errexit -o nounset -o xtrace

sudo apt-get install -y fuse
mkdir -p ~/.local/bin
curl -o ~/.local/bin/nvim -L https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
chmod u+x ~/.local/bin/nvim
