#!/bin/bash

set -o errexit -o nounset -o xtrace

sudo apt-get -y install \
    build-essential \
    bash-completion \
    curl \
    file \
    python-setuptools \
    ruby \
    cmake \
    llvm \
    clang \
    gcc \
    libc6 \
    git \
    mercurial \
    tmux \
    wget \
    htop \
    emacs \
    vim \
    mailutils \
    mosh \
    htop \
    xsel \
    silversearcher-ag \

curl -LO https://github.com/BurntSushi/ripgrep/releases/download/0.8.1/ripgrep_0.8.1_amd64.deb
sudo dpkg -i ripgrep_0.8.1_amd64.deb
rm -f ripgrep_0.8.1_amd64.deb
